/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escena;

import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import trazo_linea.Dibujo.Trazo;
/**
 *
 * @author elnin
 */
public class escenario extends javax.swing.JFrame {

    /**
     * Creates new form escenario
     */
    public escenario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_trazo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TF_X1 = new javax.swing.JTextField();
        TF_Y1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_X2 = new javax.swing.JTextField();
        Pizarra = new javax.swing.JPanel();
        Btn_clean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_trazo.setText("Trazar");
        Btn_trazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_trazoMouseClicked(evt);
            }
        });
        Btn_trazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_trazoActionPerformed(evt);
            }
        });

        jLabel1.setText("Punto A");

        jLabel2.setText("radio");

        javax.swing.GroupLayout PizarraLayout = new javax.swing.GroupLayout(Pizarra);
        Pizarra.setLayout(PizarraLayout);
        PizarraLayout.setHorizontalGroup(
            PizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        PizarraLayout.setVerticalGroup(
            PizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        Btn_clean.setText("limpiar");
        Btn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TF_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TF_Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_trazo)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_X2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_clean))
                                .addGap(34, 34, 34))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pizarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Btn_trazo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_X1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TF_X2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Btn_clean)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_trazoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_trazoMouseClicked
       
        int xc,yc,r=0;
        
        xc  =   Integer.parseInt(TF_X1.getText());
        yc  =   Integer.parseInt(TF_Y1.getText());
        r   =   Integer.parseInt(TF_X2.getText());
        
        Circulo(Pizarra.getGraphics(), xc, yc, r);
        
    }//GEN-LAST:event_Btn_trazoMouseClicked
    
    void Circulo(Graphics g, int xc, int yc, int r){

        int x, y, p;

        x = 0;

        y = r;

        p = 1 - r;

        segmento_circulo(g,xc,yc,x,y);

        /* se cicla hasta trazar todo un octante */

        while (x < y)
        {
            x = x + 1;

            if (p < 0)

            p = p + 2*x + 1;

            else {

            y = y - 1;

            p = p + 2*(x - y) + 1;

            }

            segmento_circulo(g,xc,yc,x,y);
        }
    }

    void segmento_circulo(Graphics g, int xc, int yc, int x, int y)

    {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(escenario.class.getName()).log(Level.SEVERE, null, ex);
        }

      g.drawLine(xc + x,yc + y,xc + x,yc + y);

      g.drawLine(xc - x,yc + y,xc - x,yc + y);
      
      g.drawLine(xc - y,yc + x,xc - y,yc + x);
      
      g.drawLine(xc - y,yc - x,xc - y,yc - x);
      
      g.drawLine(xc - x,yc - y,xc - x,yc - y);

      g.drawLine(xc + x,yc - y,xc + x,yc - y);
      
      g.drawLine(xc + y,yc - x,xc + y,yc - x);
      
      g.drawLine(xc + y,yc + x,xc + y,yc + x);

      //

      //---
      /**/

    }

 

/*void Circle

}*/
    private void Btn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cleanActionPerformed
        Pizarra.repaint();
    }//GEN-LAST:event_Btn_cleanActionPerformed

    private void Btn_trazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_trazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_trazoActionPerformed

    private int[] pendite(Double  m, int   x1,int   y1)
    {
        System.out.println("e--x1:" + x1 + " y1: " + y1);
        int x2,y2;
        int[] puntoa = new int[2];
        if(m<=1)
            {
                
                x2 = x1+1;
                y2 = (int)(y1 + m);
                System.out.println("--x1:" + x1 + " y1: " + y1);
                //System.out.println("x1:" + x1 + " y1: " + y1 + "x2:" + x2 + " y2: " + y2); 
                Trazo.linea(Pizarra.getGraphics(), x1, y1, x2, y2);
                //System.out.println("mincra" + m + " x" +x2 + " y" + y2);
                puntoa[0]  =   x2;
                puntoa[1]  =   y2;
            }else if(m>1)
            {
                y2 = y1+1;
                x2 = (int)(x1 + m);
                System.out.println("--2x1:" + x1 + " y1: " + y1);
                Trazo.linea(Pizarra.getGraphics(), x1, y1, x2, y2);
                System.out.println("no mincra"+ m + " x" +x2 + " y" + y2);
                puntoa[0]  =   x2;
                puntoa[1]  =   y2;
            }
        return puntoa;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new escenario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_clean;
    private javax.swing.JButton Btn_trazo;
    private javax.swing.JPanel Pizarra;
    private javax.swing.JTextField TF_X1;
    private javax.swing.JTextField TF_X2;
    private javax.swing.JTextField TF_Y1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
